### ISSUE TITLE
*.twigc files

### ISSUE THREAD

**Issue by mihai-stancu** [okdana/twigc#2]
Hi @okdana,

Thank you for `twigc` and the work behind it, great tool.

I wanted to ask a philosophical question relating to how `twigc` applies the UNIX design philosophy: currently `stdin` is assumed to be a template while the data is passed via various options. Wouldn't it make sense for it to be the other way around?

UNIX commands are very composable because they manipulate input data, apply a transformation, and output the transformed data.
If `stdin` is the raw input data, and the twig template is just a parameter then you are taking data, applying a (twig) transformation, and outputting the transformed data (ex.: html).

```
jq '.|transform' data.json | twigc -j -t template.twig | tidy > transformed_data.html

# in this case -j would be a flag telling twigc how to interpret STDIN rather than being the value itself
```

WDYT?

**Comment by mihai-stancu** [comment]
Strongly correlated with the above would be the following usecase:

Assuming we have an executable file with a `twigc` shebang (`hello_world.twigc`):
```
#!/usr/bin/twigc -j
Hello, {{ name }}!
```

We can the invoke this behavior easily via:

```
echo '{"name": "world"}' | ./hello_world.twigc
```

**Comment by okdana** [comment]
Thanks for the comments!

Firstly, maybe you already knew, but just to be clear, you can do this in your case:

```
jq '.|transform' data.json | twigc -j- template.twig | tidy > transformed_data.html
```

(`-j-` is basically a short-hand for `-j /dev/stdin`, which makes `twigc` expect the JSON data instead of the template on stdin. Using the hyphen that way is a convention that many other UNIX tools also use.)

As far as how standard input is handled in general, i'm pretty sure my thinking was based on two things:

1. You *always* need a template, but you don't *necessarily* use variables in it — the variable data is optional, hence it's provided via the options.

2. Most other UNIX software takes a document to work with on stdin. For example, `php` itself takes code (which can act as a template) that way, and by default `grep` takes data to be searched (not patterns to search for) that way. `grep` does have the `-f` option to take search patterns from a file, so you can do like `grep -f- file_to_search.txt < patterns.txt`... which is equivalent to the `twigc -j-` command i gave above. `jq` works basically the same as `grep`, i guess — the filter string is like the search pattern and the JSON file (or stdin) is like the file to search. Do you feel that's not analogous, or can you think of a counter-example?

One annoying issue with the 'overloading' approach i took with `-j` is that it's inconsistent with how `-p` and `--query` work, and i don't think it's as easily generalisable to other input formats i could add in the future, like YAML or TOML. Though maybe it doesn't need to be, idk.

As far as the 'shebang' thing, you can do that now with `-j-`, though it will leave that first line in the output. I'm not sure if making Twig templates executable is something that a lot of people would want to do, though.

**Comment by mihai-stancu** [comment]
Hi,

Yes, I made `jq + twigc` work in the command line with `twigc -j -` works like a charm.

The point I got stumped at is when trying to create an executable `*.twigc` file with `#!/usr/bin/twigc -j` because `twigc -j -` doesn't work but apparently your example with `twigc -j-` does work (10x).

Executable templates are a nice way to decouple views from data and even from the rendering engine. You could have an arbitrary number of different templating engines, all you know is that you pipe data into it and transformed data comes out.

You could build a static site generator with just json + jq + twigc + make (or yaml + yq if you swing that way).

**Comment by mihai-stancu** [comment]
I read somewhere about historical UNIX underpinnings (possibly [here](http://www.catb.org/~esr/writings/taoup/html/) or [here](https://github.com/mit-pdos/xv6-public)) which made all commands default to reading `stdin` as their main (and most of the time only) source of data.

For example `cat` wasn't initially able to take a filename as the first argument. You would invoke it with `cat < inputfile > outputfile` and since `cat` would default to reading from `stdin` and writing to `stdout` the filename processing component resided entirely in `sh`.

Later on they added features and gained arguments and options such as `-f` to specify the input file. But in order to inspect their original design I wouldn't check to see if they have `-f` or not, I'd check to see what they expect to receive in `stdin`.


- `grep` takes data into `stdin` and the patterns are via arguments
- `php` takes data into `stdin` the code is via arguments
- `jq` / `yq` / `q` all take data into `stdin` and their transformations come via arguments
- `column` / `awk` / `sed` / `gz` / `sort` / `uniq` all  take data into `stdin` and they allow options

**Comment by mihai-stancu** [comment]
Since you solved my issue with `-j-` I'm covered, thank you.

Nice talk!

**Comment by okdana** [comment]
> The point I got stumped at is when trying to create an executable *.twigc file with #!/usr/bin/twigc -j because twigc -j - doesn't work but apparently your example with twigc -j- does work (10x).

It doesn't work with `-j -` (with space) because most systems only support one argument in interpreter directives. So `#!/usr/bin/twigc -j -` is interpreted as `['/usr/bin/twigc', '-j -']`. That's just a limitation of interpreter directives, unfortunately. Some implementations of the `env` command, like FreeBSD's, have a special option to handle splitting the argument up externally, so you could do like `#!/usr/bin/env -S twigc -j -` and then it would work... but that's not portable.

If executable templates are a desirable feature, we could maybe add an option to strip the first line of the 'entry' file if it starts with `#!`. So you could do like `#!/usr/bin/twigc -xj-` or something. Feel free to make a feature request for that if you want
